name: ComicInn
description: A new Flutter project.
version: 0.2.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons: ^0.1.2
  flutter_downloader: ^1.3.3 #下载
  permission_handler: ^4.0.0 #权限管理
  package_info: ^0.4.0+4 #获取本地版本 
  file_picker: ^1.4.3+1 #文件选择
  flutter_swiper: ^1.1.6 #swiper
  fluwx: ^1.1.3 #微信sdk
  provider: ^3.1.0 #全局变量
  dio: ^3.0.5 #ajax 
  flutter_slidable: ^0.5.4 #滑动显示操作按钮
  flutter_lqrui:
    path: plugins/flutter_lqrui

  
  # jpush_flutter: ^0.1.0 #极光推送
  # janalytics: ^0.0.3 #极光统计
  # amap_base_location: ^0.4.0+1 #高德地图定位
  # sharesdk: ^1.1.8 #mob分享sdk


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    
    - assets/images/
    - assets/images/pickImage.png
  fonts:
    - family: IconFont
      fonts:
        - asset: assets/icons/iconfont.ttf
    - family: LqrFlutter
      fonts:
        - asset: plugins/flutter_lqrui/assets/icons/iconfont.ttf
